# Generated by Django 4.2.11 on 2024-03-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excert',
            field=models.TextField(blank=True),
        ),
    ]
