# Generated by Django 4.2.11 on 2024-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('drink_type', models.IntegerField(choices=[(0, 'Wines'), (1, 'Beers'), (2, 'Cocktails'), (3, 'New')], default=3)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-available'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('meal_type', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'lunch'), (2, 'Dinner'), (3, 'New')], default=3)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-meal_type'],
            },
        ),
    ]
